clone:
  depth: full

pipelines:
  custom:
    mirror-via-webhook:
      - step:
          name: Mirror to GitHub (only on master)
          script:
            - CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            - '[ "$CURRENT_BRANCH" = "master" ] || { echo "Not on master branch. Exiting."; exit 0; }'
            - git remote add github git@github.com:OndrejHajek-AutomationLabs/test.git
            - git push --mirror github
