# Nastavení úplného stažení historie pro zrcadlení
clone:
  depth: full

pipelines:
  default:
    - step:
        name: Mirror to GitHub
        script:
          # Přidání GitHubu jako druhého remote
          - git remote add github git@github.com:OndrejHajek-AutomationLabs/test.git
          # Nahrání všech větví a tagů (zrcadlení)
          - git push --mirror github